application: cryptoeditor
version: 1
runtime: python
api_version: 1

handlers:
 
- url: /images/(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))
  
- url: /download/(.*\.(msi|zip))
  static_files: static/download/\1
  upload: static/download/(.*\.(msi|zip))

- url: /cryptoeditor.css
  static_files: static/cryptoeditor.css
  upload: static/cryptoeditor.css
  
- url: /cryptoeditor2.css
  static_files: static/cryptoeditor2.css
  upload: static/cryptoeditor2.css
  
- url: /style.css
  static_files: static/style.css
  upload: static/style.css

- url: /style.ie6.css
  static_files: static/style.ie6.css
  upload: static/style.ie6.css

- url: /style.ie7.css
  static_files: static/style.ie7.css
  upload: static/style.ie7.css
  
- url: /script.js
  static_files: static/script.js
  upload: static/script.js

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /profile
  script: main.py
  secure: always
  
- url: /getprofile
  script: main.py
  secure: always
  
- url: /putlicense
  script: main.py
  secure: always
  
- url: /load
  script: main.py
  secure: always
  
- url: /save
  script: main.py
  secure: always
  
- url: /.*
  script: main.py
  
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.artx$